name: Testing SalesforceWorkFlow
on: 
  push:
    branches: 
      - develop
    paths:
      - 'force-app/**'

jobs:
    call-workflow-passing-data:
      uses: nachoborente/PublicPipelineSharedLibrary/.github/workflows/sf_workflow01.yml@main
      with:
        testvar: 'hello world, calling to sfworkflow01, test01'
        apiversion: '56.0'
      secrets: inherit
